# -*- coding: utf-8 -*-
"""BraTS_nnunet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179lamp4MjiXeBGoJ17sByzipqdUYk3i0
"""



import kagglehub
path = kagglehub.dataset_download("awsaf49/brats20-dataset-training-validation")
print(path)

import os
import glob

brats_path = os.path.join(
    path,
    "BraTS2020_TrainingData",
    "MICCAI_BraTS2020_TrainingData"
)

patients = sorted(
    glob.glob(
        os.path.join(
            brats_path,
            "BraTS20_*"
        )
    )
)

print("Patients:", len(patients))

# to rename the 355 folder
# print(patients[354])
# print(os.listdir(patients[354]))
# print(os.listdir(patients[355]))
# print(patients[355])

# patient_change = patients[354]

# old_path = os.path.join(patient_change, "W39_1998.09.19_Segm.nii")
# new_path = os.path.join(patient_change, "BraTS20_Training_355_seg.nii")

# os.rename(old_path, new_path)
# print(os.listdir(patients[354]))

# read only so cannot edit
# drop instead

import os

patients = [
    p for p in patients
    if os.path.exists(
        os.path.join(p, f"{os.path.basename(p)}_seg.nii")
    )
]
print("Total patients:", len(patients))

import os

print(brats_path)

for item in sorted(os.listdir(brats_path))[:5]:
    print(item)

import os

sample_patient = patients[0]

print(sample_patient)

for f in sorted(os.listdir(sample_patient)):
    print(f)

!pip install -q nnunetv2 SimpleITK nibabel

!nnUNetv2_plan_and_preprocess -h
import nnunetv2
print("nnU-Net imported successfully")

import os

nnunet_root = "/content/nnunet_workspace"

os.makedirs(nnunet_root, exist_ok=True)

print(nnunet_root)

dataset_dir = os.path.join(
    nnunet_root,
    "nnUNet_raw",
    "Dataset001_BraTS2020"
)

imagesTr = os.path.join(dataset_dir, "imagesTr")
labelsTr = os.path.join(dataset_dir, "labelsTr")

os.makedirs(imagesTr, exist_ok=True)
os.makedirs(labelsTr, exist_ok=True)

print(imagesTr)
print(labelsTr)

sample = patients[0]

print(os.path.basename(sample))

for f in sorted(os.listdir(sample)):
    print(f)

import shutil
from tqdm import tqdm

num_patients = 0

for patient_dir in tqdm(patients):
    patient_id = os.path.basename(patient_dir)

    flair = os.path.join(patient_dir, f"{patient_id}_flair.nii")
    t1    = os.path.join(patient_dir, f"{patient_id}_t1.nii")
    t1ce  = os.path.join(patient_dir, f"{patient_id}_t1ce.nii")
    t2    = os.path.join(patient_dir, f"{patient_id}_t2.nii")
    seg   = os.path.join(patient_dir, f"{patient_id}_seg.nii")

    # modalities
    shutil.copy2(
        flair,
        os.path.join(imagesTr, f"{patient_id}_0000.nii")
    )

    shutil.copy2(
        t1,
        os.path.join(imagesTr, f"{patient_id}_0001.nii")
    )

    shutil.copy2(
        t1ce,
        os.path.join(imagesTr, f"{patient_id}_0002.nii")
    )

    shutil.copy2(
        t2,
        os.path.join(imagesTr, f"{patient_id}_0003.nii")
    )

    # label
    shutil.copy2(
        seg,
        os.path.join(labelsTr, f"{patient_id}.nii")
    )

    num_patients += 1

print("Converted patients:", num_patients)

print("imagesTr:", len(os.listdir(imagesTr)))
print("labelsTr:", len(os.listdir(labelsTr)))

import nibabel as nib
import numpy as np

sample_mask = os.path.join(
    labelsTr,
    os.listdir(labelsTr)[0]
)

mask = nib.load(sample_mask).get_fdata()

print(np.unique(mask))

import os
import json

dataset_json = {
    "channel_names": {
        "0": "FLAIR",
        "1": "T1",
        "2": "T1CE",
        "3": "T2"
    },

    "labels": {
        "background": 0,
        "NCR_NET": 1,
        "ED": 2,
        "ET": 3
    },

    "numTraining": len(os.listdir(labelsTr)),

    "file_ending": ".nii"
}

json_path = os.path.join(dataset_dir, "dataset.json")

with open(json_path, "w") as f:
    json.dump(dataset_json, f, indent=4)

print(json_path)

with open(json_path) as f:
    print(f.read())

import os

nnUNet_raw = os.path.join(nnunet_root, "nnUNet_raw")
nnUNet_preprocessed = os.path.join(nnunet_root, "nnUNet_preprocessed")
nnUNet_results = os.path.join(nnunet_root, "nnUNet_results")

os.makedirs(nnUNet_preprocessed, exist_ok=True)
os.makedirs(nnUNet_results, exist_ok=True)

print(nnUNet_raw)
print(nnUNet_preprocessed)
print(nnUNet_results)

import os

os.environ["nnUNet_raw"] = nnUNet_raw
os.environ["nnUNet_preprocessed"] = nnUNet_preprocessed
os.environ["nnUNet_results"] = nnUNet_results

print(os.environ["nnUNet_raw"])
print(os.environ["nnUNet_preprocessed"])
print(os.environ["nnUNet_results"])

!ls /content/nnunet_workspace/nnUNet_raw

!nnUNetv2_extract_fingerprint -d 1

!nnUNetv2_plan_and_preprocess -d 1 --verify_dataset_integrity

import os
import nibabel as nib
import numpy as np

sample_file = os.path.join(labelsTr, os.listdir(labelsTr)[0])

nii = nib.load(sample_file)

mask = nii.get_fdata()

print("Before:", np.unique(mask))

mask[mask == 4] = 3

print("After :", np.unique(mask))

import os
import nibabel as nib
import numpy as np
from tqdm import tqdm

label_files = sorted(os.listdir(labelsTr))

for fname in tqdm(label_files):
    fpath = os.path.join(labelsTr, fname)

    nii = nib.load(fpath)

    mask = nii.get_fdata()

    mask[mask == 4] = 3

    mask = mask.astype(np.uint8)

    new_nii = nib.Nifti1Image(
        mask,
        affine=nii.affine,
        header=nii.header
    )

    nib.save(new_nii, fpath)

print("Done")

print(mask.dtype)

import random
import nibabel as nib
import numpy as np

for fname in random.sample(os.listdir(labelsTr), 3):
    mask = nib.load(os.path.join(labelsTr, fname)).get_fdata()
    print(fname, np.unique(mask))

with open(json_path) as f:
    print(f.read())

!nnUNetv2_plan_and_preprocess -d 1 --verify_dataset_integrity

!du -sh /content/nnunet_workspace/nnUNet_preprocessed/Dataset001_BraTS2020/*

!df -h

!nnUNetv2_train 1 3d_fullres 0

import inspect
import nnunetv2.training.nnUNetTrainer.nnUNetTrainer as trainer_module

print(trainer_module.__file__)

!pip show nnunetv2

!find /usr/local/lib/python3.12/dist-packages/nnunetv2 -name "nnUNetTrainer.py"

!grep -n "num_epochs" /usr/local/lib/python3.12/dist-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py

!find /usr/local/lib/python3.12/dist-packages/nnunetv2 -type f | grep -i supervision

!grep -R "DeepSupervision" /usr/local/lib/python3.12/dist-packages/nnunetv2 | head -20

!grep -R "deep_supervision" /usr/local/lib/python3.12/dist-packages/nnunetv2 | head -50









import os

nnunet_raw = "/kaggle/working/nnUNet_raw"
dataset_name = "Dataset001_BraTS"

base = os.path.join(
    nnunet_raw,
    dataset_name
)

imagesTr = os.path.join(base,"imagesTr")
labelsTr = os.path.join(base,"labelsTr")

os.makedirs(imagesTr, exist_ok=True)
os.makedirs(labelsTr, exist_ok=True)

print("Folders created")

import os
import shutil
import nibabel as nib
import numpy as np
from tqdm import tqdm

# Remove previous broken dataset
shutil.rmtree(
    "/kaggle/working/nnUNet_raw/Dataset001_BraTS",
    ignore_errors=True
)

# Recreate folders
base="/kaggle/working/nnUNet_raw/Dataset001_BraTS"

imagesTr=os.path.join(base,"imagesTr")
labelsTr=os.path.join(base,"labelsTr")

os.makedirs(imagesTr,exist_ok=True)
os.makedirs(labelsTr,exist_ok=True)

valid_cases=0
skipped=[]

for p in tqdm(patients):

    patient_id=os.path.basename(p)

    flair=os.path.join(
        p,
        f"{patient_id}_flair.nii"
    )

    t1=os.path.join(
        p,
        f"{patient_id}_t1.nii"
    )

    t1ce=os.path.join(
        p,
        f"{patient_id}_t1ce.nii"
    )

    t2=os.path.join(
        p,
        f"{patient_id}_t2.nii"
    )

    seg=os.path.join(
        p,
        f"{patient_id}_seg.nii"
    )

    files=[flair,t1,t1ce,t2,seg]

    if not all(os.path.exists(f) for f in files):
        skipped.append(patient_id)
        continue

    case_id=f"BraTS_{valid_cases:03d}"

    # Copy MRI modalities
    shutil.copy(
        flair,
        os.path.join(imagesTr,f"{case_id}_0000.nii.gz")
    )

    shutil.copy(
        t1,
        os.path.join(imagesTr,f"{case_id}_0001.nii.gz")
    )

    shutil.copy(
        t1ce,
        os.path.join(imagesTr,f"{case_id}_0002.nii.gz")
    )

    shutil.copy(
        t2,
        os.path.join(imagesTr,f"{case_id}_0003.nii.gz")
    )

    # Load segmentation
    img=nib.load(seg)
    mask=img.get_fdata()

    # Remap 4 -> 3
    mask=np.where(mask==4,3,mask)
    mask=mask.astype(np.uint8)

    corrected=nib.Nifti1Image(
        mask,
        img.affine,
        img.header
    )

    nib.save(
        corrected,
        os.path.join(
            labelsTr,
            f"{case_id}.nii.gz"
        )
    )

    valid_cases+=1

print("Valid:",valid_cases)
print("Skipped:",skipped)

import json

dataset_json={

"name":"BraTS",

"channel_names":{
"0":"FLAIR",
"1":"T1",
"2":"T1ce",
"3":"T2"
},

"labels":{
"background":0,
"necrotic":1,
"edema":2,
"enhancing":3
},

"numTraining":valid_cases,

"file_ending":".nii.gz"
}

with open(
    os.path.join(base,"dataset.json"),
    "w"
) as f:

    json.dump(
        dataset_json,
        f,
        indent=4
    )

print("dataset.json updated")

import os

os.environ["nnUNet_raw"]="/kaggle/working/nnUNet_raw"
os.environ["nnUNet_preprocessed"]="/kaggle/working/nnUNet_preprocessed"
os.environ["nnUNet_results"]="/kaggle/working/nnUNet_results"

!nnUNetv2_plan_and_preprocess -d 1 --verify_dataset_integrity

!nnUNetv2_train 1 3d_fullres 0

